music_rec_app/urls.py
from django.urls import path
from . import views
from . import Collaborative_Filtering
from django.urls import include

# from .views import play_song

app_name = 'music_rec_app'

urlpatterns = [
    path('',views.index, name='index'),
    path('main/', views.main, name='main'),
    path('music/', views.music, name='music'),
    path('<str:track_id>/detail/', views.detail, name='detail'),
    path('detail/<str:playlist_id>/', views.playlist_detail, name='playlist_detail'),
    path('create_playlist/', views.create_playlist, name='create_playlist'),
    path('<str:track_id>/add_to_playlist/', views.add_to_playlist, name='add_to_playlist'),
    path('<str:track_id>/remove_from_playlist/', views.remove_from_playlist, name='remove_from_playlist'),

    # path('recommend/<int:user_id>/', views.recommend_music, name='recommend_music'),
    #path('recommend_music_2/<int:user_id>/', views.recommend_music_2, name='recommend_music_2'),
    path('search/', views.searchResult, name='search'),
    path('search_genre/', views.music_search, name='search_genre'),
    path('popup/<str:track_id>', views.popup, name='popup'),

]

music_rec_app/templates/detail.html
{% extends 'base.html' %}

{% block body %}


<div onclick="history.back()" style="font-size: 28px;">
    <ion-icon name="arrow-back-circle-outline"></ion-icon>
</div>

<div class="all_container_detail">
    <div class="item_detail">
        <img src="{{ track.track_picture_url }}" alt="Track Image" class="album_img_detail" style="display: block; margin: 0 auto;">

    
    </div>

    <div class="item_detail">
        <div class="music_info" style="width: 500px;">
            <p class='names' style="font-size: 30px;"><strong>{{ track.track_name }}</strong></p>
            <p class='names'style="font-size: 26px;">{{ track.artist_name }}</p>
            <p class='names' style="font-size: 18px;">발매일 : {{ track.release_date }}</p>
            <p class='names' style="font-size: 18px;">인기도 : {{ track.track_popularity }}</p>
            <p class='names' style="font-size: 18px;">음악 장르 : {{ track.genres }}</p>
            
           {% if  track_in_playlist  %}
                {# 플레이리스트에 트랙이 있을 때 제거 버튼 보이기 #}
                <form method="post" action="{% url 'music_rec_app:remove_from_playlist' track_id=track.track_id %}">
                    {% csrf_token %}
                    <div> 별점 : {{track_in_playlist.rating}}</div>
                    <button class='plbutton' type="submit" style="font-size: 18px;"
                    onclick="showAlert2()">플레이리스트에서 빼기</button>
                </form>
            {% else %}
                {# 플레이리스트에 트랙이 없을 때 추가 버튼 보이기 #}
                <form id='myform' method="post" action="{% url 'music_rec_app:add_to_playlist' track_id=track.track_id %}" onsubmit="return validateForm()">
                    {% csrf_token %}
                    <div>                        
                        <fieldset>
                            <legend style="font-size:18px;">별점 선택하기</legend>
                            <input type="radio" name="rating_score" value="5" id="rate1"><label for="rate1">⭐</label>
                            <input type="radio" name="rating_score" value="4" id="rate2"><label for="rate2">⭐</label>
                            <input type="radio" name="rating_score" value="3" id="rate3"><label for="rate3">⭐</label>
                            <input type="radio" name="rating_score" value="2" id="rate4"><label for="rate4">⭐</label>
                            <input type="radio" name="rating_score" value="1" id="rate5"><label for="rate5">⭐</label>
                        </fieldset>       
                    </div>
                    <div>
                        <button class='plbutton' type="submit" style="font-size: 18px;">
                        플레이리스트에 추가
                        </button>
                    </div>
                </form>
            {% endif %}


        </div>
    </div>
</div>
{% endblock %}

music_rec_app/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="/static/css/style.css">

</head>
<body>
    {% comment %} <div class="bg">
        <video muted autoplay loop>
          <source src="{% static2 'video/154610.mp4' %}" type="video/mp4">
        </video>
    </div> {% endcomment %}
    <h1 class='index_title'>4.5Hz</h1>
    <span class='index_sub'> 
        {% if user.is_authenticated %}
            <a href="{% url 'music_rec_app:main' %}" style="font-size: 20px" class="nav_link">Main</a>
        {% else %}
            <a href="{% url 'accounts:signup' %}" style="font-size: 20px" class="nav_link">Signup</a>
            <a href="{% url 'accounts:login' %}" style="font-size: 20px" class="nav_link">Login</a>
        {% endif %}{% comment %} style="width:200px; height:100px; position:absolute; top:70%; left: 50%;margin: -50px 0 0 -100px;" {% endcomment %}
    </span>
    <link rel="stylesheet" href="/static/css/style.css">

</body>
</html>

music_rec_app/templates/main.html
{% extends 'base.html' %}

{% block body %}


<h1 class="main_title">{{username}}님에게 추천하는 노래</h1>

<div class="track-container">
    {% if track_list %}
        {% for track in track_list %}
            <div class="track-card">
                <a href="{% url 'music_rec_app:detail' track_id=track.track_id %}">
                    <img src="{{ track.track_picture_url }}" alt="Track Image" class="album_img">
                    <p class='names'><strong>{{ track.track_name }}</strong></p>
                    <p class='names'>{{ track.artist_name }}</p>
                </a>
            </div>
        {% endfor %}
    {% else %}
        {% for track in random_track %}
        <div class="track-card">
            <a href="{% url 'music_rec_app:detail' track_id=track.track_id %}">
                <img src="{{ track.track_picture_url }}" alt="Track Image" class="album_img">
                <p class='names'><strong>{{ track.track_name }}</strong></p>
                <p class='names'>{{ track.artist_name }}</p>
            </a>
        </div>
        {% endfor %}
    {% endif %}
</div>

{% endblock %}

music_rec_app/templates/music.html
{% extends 'base.html' %}
{% block body %}

<div class="all-container">
    <div class="item">

        {% comment %} <div class="column-container">
            <h2>지금 듣고 있는 노래</h2>
            {% for track in current_track %}
                <div class="image-container">
                    <a href="{% url 'music_rec_app:detail' track_id=track.track_id %}">
                    <img src="{{ track.track_picture_url }}" alt="{{ track.track_name }}" class="img">
                    </a>
                    <div class='names'>
                        <a href="{% url 'music_rec_app:detail' track_id=track.track_id %}">
                        <p class='names'><strong>{{ track.track_name }}</strong></p>
                        <p class='names'>{{ track.artist_name }}</p>
                        </a>
                    </div>
                </div>
            {% endfor %}

        <div class = "col-md-4 col-lg-3">
            <div class="card text-bg-light mb-3" style="max-width: 540px;">
                <h5 class="card-header">음악 검색</h5>
                <div class="card-body">
                    <div class="input-group">
                        <input class="form-control form-control-lg" type="text" placeholder="Search for..." id="search-input">
                        <span class="input-group-btn">
                            <button class="btn btn-secondary" type="button" onclick="searchPost()">Search</button>
                        </span>
                    </div>
                </div>
            </div>
        </div>

        </div> {% endcomment %}
        <div class="column-container">
            <h2> 음악 검색 </h2>
                <div class="card-body">
                    <div class="input-group">
                        <form class="form-inline my-2 my-lg-0" action="{% url 'music_rec_app:search' %}" method="get">
                            {%csrf_token%}
                            <input class="form-control form-control-lg" type="text" placeholder="검색어 입력" name="q" style="width: 300px; height:40px">
                            <span class="input-group-btn">
                                <button class="btn btn-secondary" type="submit" style=" width: 80px; height:40px">검색</button>
                            </span>
                        </form>
                    </div>
                </div>
            </div>

        <div class="column-container">
            <h2>장르 모아보기</h2>
            <div class="card-body">
                <div class="input-group">
                    <form class="form-inline my-2 my-lg-0" action="{% url 'music_rec_app:search_genre' %}" method="get">
                        {% csrf_token %}
                        <div>
                            <select name="genre" id="genre" required style="width: 200px; height: 40px">
                                <option value="" selected disabled>장르 고르기</option>
                                <option value="acoustic">Acoustic</option>
                                <option value="dance">Dance</option>
                                <option value="edm">EDM</option>
                                <option value="hip-hop">Hip-hop</option>
                                <option value="k-pop">K-pop</option>
                                <option value="pop">POP</option>
                                <option value="r-n-b">R&B</option>
                                <option value="rock">Rock</option>
                                <option value="romance">Romance</option>
                                <option value="soul">Soul</option>
                            </select> 
                            <input type="submit" value="검색" style="width: 80px; height: 40px">
                        </div>
                    </form>
                    
                </div>
            </div>
        </div>
            
        
        <div class="column-container">

            {% if hot_songs_2 %}

                <h2>{{user_age_range}}대 {{user_gender}}에게 가장 핫한 노래</h2>
                {% for track in hot_songs_2 %}
                    <div class="image-container"> 
                        <a href="{% url 'music_rec_app:detail' track_id=track.track_id %}">
                        <img src="{{ track.track_picture_url }}" alt="{{ track.track_name }}" class="img" >
                        </a>
                        <div>
                            <a href="{% url 'music_rec_app:detail' track_id=track.track_id %}">
                            <p class='names'><strong>{{ track.track_name }}</strong></p>
                            <p class='names'>{{ track.artist_name }}</p>
                            </a>
                        </div>
                    </div>
                {% endfor %}
            {% endif %}
        </div>

        <div class="column-container">

            <h2>나의 플레이리스트</h2>
            {% if user_playlist_id %}

                {% for playlist_id in user_playlist_id %}
                    <div class="image-container">
                        <a href="{% url 'music_rec_app:playlist_detail' playlist_id=playlist_id %}">
                        <img src="{{ default_playlist_image }}" alt="Default playlist image" class="img">
                        </a>
                        <div class='names'>
                            <a href="{% url 'music_rec_app:playlist_detail' playlist_id=playlist_id %}">
                            <p class='names'><strong>Playlist #{{playlist_id}}</strong></p>
                            </a>
                        </div>
                    </div> 
                {% endfor %}

            {% else %}
            <!-- If user_playlist_id is empty, display a button to create a new playlist -->
                <a href="{% url 'music_rec_app:create_playlist' %}">
                    <button style="width: 200px; height: 40px">플레이리스트 만들기</button>
                </a>
            {% endif %}
        </div>
        <div class="column-container">

            {% if hot_songs_1 %}
                <h2>나를 위한 새로운 발견</h2>
                {% for track in hot_songs_1 %}
                    <div class="image-container">
                        <a href="{% url 'music_rec_app:detail' track_id=track.track_id %}">
                        <img src="{{ track.track_picture_url }}" alt="{{ track.track_name }}" class="img">
                        </a>
                        <div class='names'>
                            <a href="{% url 'music_rec_app:detail' track_id=track.track_id %}">
                            <p class='names'><strong>{{ track.track_name }}</strong></p>
                            <p class='names'>{{ track.artist_name }}</p>
                            </a>
                        </div>
                    </div>
                {% endfor %}
            {% endif %}
        </div>
{% comment %}         
        <div class="column-container">
            <h2>접속한 사용자를 위한 음악 추천 </h2>
            {% for track in recommended_playlists %}
                <div class="image-container">
                    <a href="{% url 'music_rec_app:detail' track_id=track.track_id %}">
                        <img src="{{ track.track_picture_url }}" alt="{{ track.track_name }}" class="img">
                    </a>
                    <div>
                        <a href="{% url 'music_rec_app:detail' track_id=track.track_id %}">
                            <p class='names'><strong>{{ track.track_name }}</strong></p>
                            <p class='names'>{{ track.artist_name }}</p>
                        </a>
                    </div>
                </div>
            {% endfor %}
        </div> {% endcomment %}

        <div>
            <h2>4.5Hz차트</h2>
            <div style="text-align: right;"> 
                <form method="GET" action="">
                    <select id="time" name="time">
                        <option value="" selected disabled>시간대 선택</option>
                        {% for time in unique_times %}
                            <option value="{{time}}">{{time}}</option>
                        {% endfor %}
                    </select> 
                    <input type="submit" value="확인">
                </form>
            </div>
            <table class="table" style="width:100%">
                <tr class = "person_track_title">
                    <th><strong>순위</strong></th>
                    <th><strong></strong></th>
                    <th><strong>가수명</strong></th>
                    <th><strong>제목</strong></th>
                    <th><strong>재생</strong></th>
                    <th><strong>start</strong></th>
                    <th><strong>end</strong></th>
                </tr>
                {% if not request.GET.time %}
                    {% for track in current_result %}
                        <tr class="person_track_row">  
                            <td><strong>{{forloop.counter}}</strong></td>
                            <td><img src="{{ track.0 }}"style="height: 50px;width: 50px;"></td>
                            <td>{{ track.1 }}</td>  
                            <td>{{ track.2 }}</td>
                            <td>{{ track.3 }}</td>
                            <td>{{ track.4 }}</td>
                            <td>{{ track.5 }}</td>
                        </tr>
                    {% endfor %}
                {% else %}
                    {% for track in result %}
                        <tr class="person_track_row">  
                            <td><strong>{{forloop.counter}}</strong></td>
                            <td><img src="{{ track.0 }}"style="height: 50px;width: 50px;"></td>
                            <td>{{ track.1 }}</td>  
                            <td>{{ track.2 }}</td>
                            <td>{{ track.3 }}</td>
                            <td>{{ track.4 }}</td>
                            <td>{{ track.5 }}</td>
                        </tr>
                    {% endfor %}
                {% endif %}
            </table>
        </div>
        
    
    </div>

    <div class="item2" >
        <h2>Top50 차트</h2>
        <p>현재 가장 많이 재생된 트랙의 일일 업데이트</p>
            <table class="table" style="width:100%">
                <tr class = "person_track_title">
                    <th><strong>순위</strong></th>
                    <th><strong></strong></th>
                    <th><strong>제목</strong></th>
                    <th><strong>가수명</strong></th>
                </tr>
                {% for track in top_50_track %}
                        <tr class="person_track_row">  
                            <td><strong>{{forloop.counter}}</strong></td>
                            <td>
                                <a href="{% url 'music_rec_app:detail' track_id=track.track_id %}"><img src="{{ track.track_picture_url }}" alt="{{ track.track_name }}" style="height: 50px;width: 50px;"></td></a>
                            </td>
                            <td>
                                <a href="{% url 'music_rec_app:detail' track_id=track.track_id %}">{{ track.track_name }}</a>
                            </td>
                            <td>
                                <a href="{% url 'music_rec_app:detail' track_id=track.track_id %}">{{ track.artist_name }}</a>
                            </td>  
                        </tr>
                {% endfor %}
            </table>
    </div>
   
</div>


{% comment %} <aside class="sidebar" style="position: fixed; overflow-y: auto; display: show;">
    <ul class="kpop_rank">
        <p>kpop_rank</p>
        <li></li>
    </ul>

    <ul class="gender_rec">
        <li>gender_rec</li>
        <li></li>
    </ul>

    <ul class="playlist">
        <li>playlist</li>
    </ul>

</aside> {% endcomment %}

{% comment %} <button onclick="toggleSidebar()">Toggle Sidebar</button> {% endcomment %}

{% endblock %}

music_rec_app/templates/playlist_detail.html
{% extends 'base.html' %}

{% block body %}


<div onclick="history.back()" style="font-size: 28px;">
    <ion-icon name="arrow-back-circle-outline"></ion-icon>
</div>   


<div class="track-container">
    {% for track in inplaylist_tracks %}
        <div class="track-card-playlist">
            <a href="{% url 'music_rec_app:detail' track_id=track.track_id %}">
                <img src="{{ track.track_picture_url }}" alt="Track Image" class="playlist_album">
                <p class='inpl_names'><strong>{{ track.track_name }}</strong></p>
                <p class='inpl_names'>{{ track.artist_name }}</p>
            </a>
        </div>
    {% endfor %}

</div>

{% endblock %}

music_rec_app/templates/search.html
{% extends 'base.html' %}

{% block body %}


<h1 class="text-center my_search_text"><b>"{{ query }}"</b>에 대한 검색 결과</h1>


        {% comment %} <div class="track-card">
        <a href="{% url 'music_rec_app:detail' track_id=product.track_id %}">
            <img class-"album_img" src="{{product.track_picture_url}}" alt="product.name">
        </a>
        <div class='names'>
            <p>{{product.track_name}}</p>
            <p>{{product.artist_name}}</p>
        </div> {% endcomment %}

<div class="track-container">
    {% for product in products %}
        <div class="track-card-playlist">
            <a href="{% url 'music_rec_app:detail' track_id=product.track_id %}">
                <img src="{{ product.track_picture_url }}" alt="Track Image" class="playlist_album">
                <p class='inpl_names'><strong>{{ product.track_name }}</strong></p>
                <p class='inpl_names'>{{ product.artist_name }}</p>
            </a>
        </div>
    {% empty %}
    <div class="row mx-auto">
        <p class="text-center my_search_text">0건의 결과가 있습니다.</p>
    </div>
{% endfor %}

{% endblock %}

music_rec_app/templates/search_genre.html
{% extends 'base.html' %}

{% block body %}


<h1 class="text-center my_search_text"><b>"{{ query }}"</b> 모아보기 </h1>

<div class="track-container">
    {% for genre in genres %}
        <div class="track-card-playlist">
            <a href="{% url 'music_rec_app:detail' track_id=genre.track_id %}">
                <img src="{{ genre.track_picture_url }}" alt="Track Image" class="playlist_album">
                <p class='inpl_names'><strong>{{ genre.track_name }}</strong></p>
                <p class='inpl_names'>{{ genre.artist_name }}</p>
            </a>
        </div>
    {% empty %}
    <div class="row mx-auto">
        <p class="text-center my_search_text">0건의 결과가 있습니다.</p>
    </div>
{% endfor %} 

{% endblock %}