accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'accounts'

urlpatterns = [
    path('signup/',views.signup, name='signup'),
    path('login/', views.login, name='login'),
    # path('logout/', views.logout, name = 'logout'),
    path('logout/', auth_views.LogoutView.as_view(next_page='music_rec_app:index'), name='logout'),
]

final_pjt/urls.py
from django.contrib import admin
from django.urls import path, include
from music_rec_app import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('music_rec_app.urls')),
    path('total_static/',include('static_app.urls') ),
    path('accounts/',include('accounts.urls')),
    path('spotify/', include('spotify.urls'))
]

music_rec_app/urls.py
from django.urls import path
from . import views
from . import Collaborative_Filtering
from django.urls import include

# from .views import play_song

app_name = 'music_rec_app'

urlpatterns = [
    path('',views.index, name='index'),
    path('main/', views.main, name='main'),
    path('music/', views.music, name='music'),
    path('<str:track_id>/detail/', views.detail, name='detail'),
    path('detail/<str:playlist_id>/', views.playlist_detail, name='playlist_detail'),
    path('create_playlist/', views.create_playlist, name='create_playlist'),
    path('<str:track_id>/add_to_playlist/', views.add_to_playlist, name='add_to_playlist'),
    path('<str:track_id>/remove_from_playlist/', views.remove_from_playlist, name='remove_from_playlist'),

    # path('recommend/<int:user_id>/', views.recommend_music, name='recommend_music'),
    #path('recommend_music_2/<int:user_id>/', views.recommend_music_2, name='recommend_music_2'),
    path('search/', views.searchResult, name='search'),
    path('search_genre/', views.music_search, name='search_genre'),
    path('popup/<str:track_id>', views.popup, name='popup'),

]

static_app/urls.py
from django.urls import path, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from . import views

app_name = 'static_app'

urlpatterns = [
    path('', views.show_static, name ='static_home'),
    path('personal/', views.show_personal_static, name = 'personal_static'),
    # path('personal/', views.spotify_login, name = 'spotify_login'),

]

urlpatterns += staticfiles_urlpatterns()

templates/_nav.html
{% load static %}

{% comment %} <nav class="navbar navbar-vertical-left"> {% endcomment %}

    {% comment %} <style>
      body { {% endcomment %}
          {% comment %} background-image: url("/static/images/back.png"); {% endcomment %}
          {% comment %} color: white;
          background-color: #12192c;
          background-size: cover;
          background-repeat: no-repeat;
          background-position: center -40px;
      }
    </style> {% endcomment %}
    


  <div class="l-navbar" id="navbar">
      <nav class="nav">
          <div>
              <div class="nav__brand">
                  <ion-icon name="menu-outline" class="nav__toggle" id="nav-toggle"></ion-icon>
                  <a href="{% url 'music_rec_app:index' %}" class="nav__logo">4.5Hz</a>
              </div>         
              <div class="nav__list">
                  <a href="{%url 'music_rec_app:main'%}" class="nav__link {% if request.path == '/main/' %}active{% endif %}">
                    {% comment %} <i class="bi bi-house-fill" style="size:30;"> 홈</i> {% endcomment %}
                    <ion-icon name="home-outline" class="nav__icon"></ion-icon>
                    <span class="nav_name">추천 음악</span>
                  </a>

                  <a href="{%url 'music_rec_app:music'%}" class="nav__link {% if request.path == '/music/' %}active{% endif %}"> 
                      {% comment %} <i class="bi bi-music-note-beamed">음악</i> {% endcomment %}
                      <ion-icon name="musical-notes-outline" class="nav__icon"></ion-icon>                      
                      <span class="nav_name">음악서랍</span>
                  </a>

                  <a href="{%url 'static_app:static_home'%}" class="nav__link {% if request.path == '/total_static/' %}active{% endif %}">
                      {% comment %} <i class="bi bi-globe-asia-australia">정보</i> {% endcomment %}
                      <ion-icon name="earth-outline" class="nav__icon"></ion-icon>                    
                      <span class="nav_name">모두의 음악기록</span>
                  </a>

                  <a href="{%url 'static_app:personal_static'%}" class="nav__link {% if request.path == '/total_static/personal/' %}active{% endif %}">
                      {% comment %} <i class="bi bi-person-fill">사용자</i> {% endcomment %}
                      <ion-icon name="person-outline" class="nav__icon"></ion-icon>                      
                      <span class="nav_name">나만의 음악기록</span>
                  </a>

              </div>
              <a href="{% url 'accounts:logout' %}" class="nav__link">
                  <ion-icon name="log-out-outline" class="nav__icon"></ion-icon>
                  <span class="nav_name">Log out</span>
              </a>
          </div>
      </nav>
  </div>

  
  {% comment %} {% url 'accounts:logout' %}?next={% url 'music_rec_app:index' %} {% endcomment %}
{% comment %} </nav> {% endcomment %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    {% comment %} <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous"> {% endcomment %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    {% comment %} {% load static %} {% endcomment %}
    <link rel="stylesheet" href="/static/css/style.css">
</head>
<body id="body-pd">

            {% include '_nav.html' %}

        <div class="container">
            {% block body %}
            {% endblock %}
        </div>
    
    {% comment %} <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>    {% endcomment %}
    <script src="https://unpkg.com/ionicons@5.2.3/dist/ionicons.js"></script>
    <script src="/static/js/main.js"></script>

</body>
</html>